#!/bin/bash

source ../settings/scripts/_common.sh

ynh_print_info "Declaring SeerrNG files for backup..."
ynh_backup --src_path="$install_dir"
ynh_backup --src_path="$data_dir"
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup --src_path="/etc/systemd/system/$app.service"

ynh_print_info "SeerrNG backup declaration completed"
